### ISSUE TITLE
I have ClassCastException

### ISSUE THREAD

**Issue by psu1025** [logstash/logstash-logback-encoder#111]
Hi, I'm try logstash-logback-encoder attach for my tomcat access log.

And, stucked because of this error.

```
16:27:41,010 |-ERROR in net.logstash.logback.appender.LogstashSocketAppender[stash] - Appender [stash] failed to append. java.lang.ClassCastException: ch.qos.logback.access.spi.AccessEvent cannot be cast to ch.qos.logback.classic.spi.ILoggingEvent
        at java.lang.ClassCastException: ch.qos.logback.access.spi.AccessEvent cannot be cast to ch.qos.logback.classic.spi.ILoggingEvent
        at      at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.getTimestampAsMillis(LoggingEventFormattedTimestampJsonProvider.java:20)
        at      at net.logstash.logback.composite.FormattedTimestampJsonProvider.getFormattedTimestamp(FormattedTimestampJsonProvider.java:57)
        at      at net.logstash.logback.composite.FormattedTimestampJsonProvider.writeTo(FormattedTimestampJsonProvider.java:53)
        at      at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)
        at      at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:169)
        at      at net.logstash.logback.composite.CompositeJsonFormatter.writeEventAsString(CompositeJsonFormatter.java:159)
        at      at net.logstash.logback.layout.CompositeJsonLayout.doLayout(CompositeJsonLayout.java:47)
        at      at net.logstash.logback.layout.CompositeJsonLayout.doLayout(CompositeJsonLayout.java:28)
        at      at ch.qos.logback.core.net.SyslogAppenderBase.append(SyslogAppenderBase.java:103)
        at      at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:85)
        at      at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
        at      at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:201)
        at      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at      at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at      at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at      at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at      at java.lang.Thread.run(Thread.java:724)
```

I'm try attach logback library (version 1.3.3) and logstash-logback-encoder(version 4.4) library to  tomcat's CLASSPATH.

logback-access.xml is this. (same as a example)
```
<configuration>
  <appender name="stash" class="net.logstash.logback.appender.LogstashAccessTcpSocketAppender">
      <!-- remoteHost and port are optional (default values shown) -->
      <remoteHost>127.0.0.1</remoteHost>
      <port>4560</port>

      <!-- encoder is required -->
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  </appender>

  <appender-ref ref="stash" />
</configuration>
```
My full tomcat library list is this.
```
annotations-api.jar
catalina-ant.jar
catalina-ha.jar
catalina.jar
catalina-tribes.jar
commons-codec-1.6.jar
commons-io-2.4.jar
ecj-P20140317-1600.jar
el-api.jar
guava-14.0.1.jar
jackson-annotations-2.3.3.jar
jackson-core-2.3.3.jar
jackson-databind-2.3.3.jar
jasper-el.jar
jasper.jar
jsp-api.jar
jul-to-slf4j-1.7.5.jar
logback-access-1.1.3.jar
logback-classic-1.1.3.jar
logback-core-1.1.3.jar
logstash-logback-encoder-4.4.jar
mysql-connector-java-5.1.25.jar
raven-5.0.1.jar
raven-logback-5.0.1.jar
servlet-api.jar
slf4j-api-1.7.5.jar
slf4j-simple-1.7.12.jar
tomcat7-websocket.jar
tomcat-api.jar
tomcat-coyote.jar
tomcat-dbcp.jar
tomcat-i18n-es.jar
tomcat-i18n-fr.jar
tomcat-i18n-ja.jar
tomcat-jdbc.jar
tomcat-util.jar
websocket-api.jar
```

Please help me.

Thank you.

**Comment by psu1025** [comment]
Resole this problem.
I change my encoder
```
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder" />
```
Thanks.
