### ISSUE TITLE
logstash-logback-encoder not working on Android

### ISSUE THREAD

**Issue by hbprotoss** [logstash/logstash-logback-encoder#142]
hi, we are using logstash-logback-encoder on Android, but logstash-logback-encoder uses a method `java.util.concurrent.ScheduledThreadPoolExecutor.setRemoveOnCancelPolicy` that is not supported by dalvikvm under API 21.

```
DexOpt: illegal method access (call Ljava/util/concurrent/ScheduledThreadPoolExecutor;.setRemoveOnCancelPolicy (Z)V from Lnet/logstash/logback/appender/AsyncDisruptorAppender;)
Could not find method java.util.concurrent.ScheduledThreadPoolExecutor.setRemoveOnCancelPolicy, referenced from method net.logstash.logback.appender.AsyncDisruptorAppender.setRemoveOnCancelPolicy
VFY: unable to resolve virtual method 34048: Ljava/util/concurrent/ScheduledThreadPoolExecutor;.setRemoveOnCancelPolicy (Z)V
VFY: replacing opcode 0x6e at 0x0009
Exception Ljava/lang/RuntimeException; thrown while initializing Lnet/logstash/logback/encoder/com/lmax/disruptor/util/Util;
Exception Ljava/lang/ExceptionInInitializerError; thrown while initializing Lnet/logstash/logback/encoder/com/lmax/disruptor/RingBufferFields;
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.ExceptionInInitializerError
    at net.logstash.logback.encoder.com.lmax.disruptor.dsl.Disruptor.<init>(Disruptor.java:98)
    at net.logstash.logback.appender.AsyncDisruptorAppender.start(AsyncDisruptorAppender.java:359)
    at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender.start(AbstractLogstashTcpSocketAppender.java:805)
    at ch.qos.logback.core.joran.action.AppenderAction.end(Unknown Source)
    at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source)
    at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
    at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source)
    at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
    at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source)
    at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source)
    at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source)
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
```

I'm wondering if there is a way to avoid calling this method? Does it have any problems not setting the RemoveOnCancelPolicy?

THX

**Comment by philsttr** [comment]
Hi @hbprotoss,

When keepAlive is enabled, calling `setRemoveOnCancelPolicy` is required to properly shutdown the appender when a shutdown is requested.  If not called, the appender will wait until the next scheduled keepAlive event before it shuts down.  See issue #114 for more info regarding why this call was added.

Having said that, `setRemoveOnCancelPolicy` is only called if that method is available at runtime.

See the logic [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java#L432-L461)

I haven't ever done any programming on android, so I'm not sure how to avoid the exception you are seeing.  The code already checks to see if the method is available, and doesn't call it if it is not available.  Do you have any other suggestions on how to check to see if it's available (that works on android and non-android jvms)?

**Comment by philsttr** [comment]
Closing this as it appears that recent versions of the android runtime include the setRemoveOnCancelPolicy method

https://developer.android.com/reference/java/util/concurrent/ScheduledThreadPoolExecutor.html#setRemoveOnCancelPolicy(boolean)
