### ISSUE TITLE
Not compatible with Spring Boot 1.3.3 (upgrading logback to 1.1.5)

### ISSUE THREAD

**Issue by PierreBesson** [logstash/logstash-logback-encoder#153]
Hi guys,

The Spring Boot project has released version 1.3.3 and they have upgraded logback from 1.1.3 to 1.1.5 (see [the relevant commit](https://github.com/spring-projects/spring-boot/commit/1735fac3ab576be5a05439ac1cfe9227a84269fe)). This seems not to be compatible with the current version of logstash-logback-encoder.

Starting my spring boot 1.3.3 sample app, I have the following stacktrace and the app refuse to boot.
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/pattern/Converter;)V
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:88)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:50)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:143)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:122)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:378)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:328)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
	at io.jhipster.dockermicroservices.T1App.<clinit>(T1App.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
	at java.lang.Thread.run(Thread.java:745)
```

- Removing the dependency to logstash-logback-encoder fixes it.
- Downgrading to Spring boot 1.3.2 fixes it.

Thank you in advance.
Best regards,
Pierre Besson

**Comment by PierreBesson** [comment]
To follow up on this. I added exclusions on logback dependencies in my logstash-logback-encoder import. So the problem is fixed. Maybe this could be added as a tip in your documentation.
Sorry to have bothered you asking you to support integration with other projects.

**Comment by philsttr** [comment]
Hi Pierre,

Are you sure this is due to logstash-logback-encoder?  The stacktrace doesn't even mention any classes from logstash-logback-encoder.  At first glance, it just looks like a mismatch between logback-classic and logback-core.  Make sure you are using the same version for both of those libraries.  Logback-classic 1.1.5 probably won't work with logback-core 1.1.3 or vice versa.

You can use maven's dependency management section to ensure you are using the same version.

Excluding the logback dependency from logstash-logback-encoder is probably just making it so the logback-classic/core versions used by logstash-logback-encoder do not come into consideration when maven calculates the version to actually use.

**Comment by PierreBesson** [comment]
Thank you for your answer. Yes the issue was that I was using logback-classic 1.1.5. I now see that it is simple do deal with this issue with dependency management. You can close this issue as it is a problem on my side. Thanks again for your help.

**Comment by loykianos** [comment]
Hey, I have a very similar issue. How did you end up solving this?

**Comment by markbigler** [comment]
Adding these lines to your pom.xml should fix the problem temporary:

		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>4.6</version>
			<exclusions>
				<exclusion>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by LaCodeA** [comment]
Ugrading to Spring Boot 1.3.5 fixed this for me

**Comment by linfangwu** [comment]
exclude spring-boot-starter-logging from spring boot, add logback-classic in dependencies fixed the problem.

Lin Wu

**Comment by msymons** [comment]
Looks like Spring Boot  will use logback 1.2.3 in v2.0.0.  Same version of logback as used in logstash-logback-encoder 4.10 and 4.11

**Comment by WesternGun** [comment]
I use `gradle dependencyInsight --dependency logback` to check the dependency tree, and I saw that, Spring Boot starter-logging 2.1.9 seems to be using `logback 1.1.3`. 
```
> Task :dependencyInsight
ch.qos.logback:logback-classic:1.1.3 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]

ch.qos.logback:logback-classic:1.1.3
\--- compileClasspath

ch.qos.logback:logback-classic:1.2.3 -> 1.1.3
\--- org.springframework.boot:spring-boot-starter-logging:2.1.9.RELEASE
     \--- org.springframework.boot:spring-boot-starter:2.1.9.RELEASE
          +--- compileClasspath (requested org.springframework.boot:spring-boot-starter)
          +--- org.springframework.boot:spring-boot-starter-web:2.1.9.RELEASE
          |    +--- compileClasspath (requested org.springframework.boot:spring-boot-starter-web)
          |    \--- org.springframework.boot:spring-boot-starter-websocket:2.1.9.RELEASE
          |         \--- compileClasspath
          +--- org.springframework.boot:spring-boot-starter-json:2.1.9.RELEASE
          |    +--- org.springframework.boot:spring-boot-starter-web:2.1.9.RELEASE (*)
          |    \--- org.springframework.boot:spring-boot-starter-jersey:2.1.9.RELEASE
          |         \--- compileClasspath (requested org.springframework.boot:spring-boot-starter-jersey)
          \--- org.springframework.boot:spring-boot-starter-validation:2.1.9.RELEASE
               \--- org.springframework.boot:spring-boot-starter-jersey:2.1.9.RELEASE (*)

ch.qos.logback:logback-core:1.1.3 (selected by rule)
   variant "compile" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.category            = library (not requested)

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]

ch.qos.logback:logback-core:1.1.3
+--- compileClasspath
\--- ch.qos.logback:logback-classic:1.1.3
     +--- compileClasspath
     \--- org.springframework.boot:spring-boot-starter-logging:2.1.9.RELEASE (requested ch.qos.logback:logback-classic:1.2.3)
          \--- org.springframework.boot:spring-boot-starter:2.1.9.RELEASE
               +--- compileClasspath (requested org.springframework.boot:spring-boot-starter)
               +--- org.springframework.boot:spring-boot-starter-web:2.1.9.RELEASE
               |    +--- compileClasspath (requested org.springframework.boot:spring-boot-starter-web)
               |    \--- org.springframework.boot:spring-boot-starter-websocket:2.1.9.RELEASE
               |         \--- compileClasspath
               +--- org.springframework.boot:spring-boot-starter-json:2.1.9.RELEASE
               |    +--- org.springframework.boot:spring-boot-starter-web:2.1.9.RELEASE (*)
               |    \--- org.springframework.boot:spring-boot-starter-jersey:2.1.9.RELEASE
               |         \--- compileClasspath (requested org.springframework.boot:spring-boot-starter-jersey)
               \--- org.springframework.boot:spring-boot-starter-validation:2.1.9.RELEASE
                    \--- org.springframework.boot:spring-boot-starter-jersey:2.1.9.RELEASE (*)
```

And I change my `logback-core` to `1.1.3` and the problem is gone.

```groovy
compile group: 'ch.qos.logback', name: 'logback-core', version: '1.1.3'
```
