### ISSUE TITLE
Can't use LoggingEventCompositeJsonEncoder with LogstashSocketAppender, prints "no applicable action for"

### ISSUE THREAD

**Issue by w32blaster** [logstash/logstash-logback-encoder#203]
Hi there,

not sure whether this is issue or I am doing something wrong. Let me describe my case.

# Preamble.
I have the application written on Spring Boot (version 1.4.2.RELEASE) and I collect all the logs and sent them to logstash over UDP to remote server in JSON format. Everything works fine. Here is my code that works:

```
  <appender name="stash" class="net.logstash.logback.appender.LogstashSocketAppender">
    <host>1.2.3.4</host>
    <port>10514</port>
    <includeMdc>true</includeMdc>
    <includeContext>true</includeContext>
    <timeZone>UTC</timeZone>
</appender>
```

# What I try to change?
And now I want to add few Event-specific Custom Fields to outcoming JSON. I added the _keyValue_ parameters to my loggings, like so:

```
logger.info("log message", keyValue("name", "value"));
```
but I can't see these new values in the outcoming JSON. According to the documentation, _"StructuredArguments will only be included in the JSON output if using composite encoders/layouts with the arguments provider."_ So, I tried to add this encoder to my configuration.

# Problem
I tried to play with different arguments, but in any case I got the message:

```
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:84 - no applicable action for [encoder], current ElementPath  is [[configuration][appender][encoder]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:19 - no applicable action for [providers], current ElementPath  is [[configuration][appender][encoder][providers]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@19:15 - no applicable action for [mdc], current ElementPath  is [[configuration][appender][encoder][providers][mdc]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@33:22 - no applicable action for [arguments], current ElementPath  is [[configuration][appender][encoder][providers][arguments]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@35:21 - no applicable action for [stackTrace], current ElementPath  is [[configuration][appender][encoder][providers][stackTrace]]
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:161)
        at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
        at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:50)
        at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
        at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:299)
```

Here is my code I try to apply:

```
<appender name="stash" class="net.logstash.logback.appender.LogstashSocketAppender">
    <host>1.2.3.4</host>
    <port>10514</port>
    <includeMdc>true</includeMdc>
    <includeContext>true</includeContext>
    <timeZone>UTC</timeZone>

    <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
       <providers>
        <mdc/>
        <arguments />
      </providers>
    </encoder>
  </appender>
```

I tried to rename **logstash.xml** to  **logstash-spring.xml**, but I got the same result. 

Interesting fact, that if I use another appender, such as ConsoleAppender, everything works and I can see added Event Custom fileds in the printed JSON. But it doesn't work only with **LogstashSocketAppender**. 

Can you please suggest me what I am doing wrong, please? Thank you!

**Comment by w32blaster** [comment]
I am using these versions:
```
    compile ('net.logstash.logback:logstash-logback-encoder:4.8')
    compile ('ch.qos.logback.contrib:logback-json-classic:0.1.5')
    compile ('ch.qos.logback.contrib:logback-jackson:0.1.5')
    compile ('ch.qos.logback:logback-access:1.1.10')
```

**Comment by philsttr** [comment]
Unfortunately, since `LogstashSocketAppender` is based on logback's `SyslogAppenderBase`, which embeds the `Layout`, it's a little difficult to configure.  Fortunately, it's still possible.  You can do it like this:

```xml
<appender name="stash" class="net.logstash.logback.appender.LogstashSocketAppender">
    <host>1.2.3.4</host>
    <port>10514</port>
    <includeMdc>true</includeMdc>
    <includeContext>true</includeContext>
    <timeZone>UTC</timeZone>
    <provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider"/>
</appender>
```

Note that after #169 is implemented, the `ArgumentsJsonProvider` will be added to the `LogstashSocketAppender` by default.

**Comment by w32blaster** [comment]
Thank you for the quick response. Yep, your suggestion works. I can see the Event Custom fields in my Kibana reports. Thank you very much!
