### ISSUE TITLE
NoSuchMethodError Encoder#init(..) in AbstractLogstashTcpSocketAppender

### ISSUE THREAD

**Issue by openwms** [logstash/logstash-logback-encoder#229]
With logback-core 1.2.x the Encoder has changed and the init(..) method is gone. This breaking API changes requires a major release but has been introduced in a minor version update. Anyway `ch.qos.logback.core.encoder.Encoder#init(OutputStream)` is gone.

Using logstash-logback-encoder in 4.9 with logback 1.2.x leads to the following exception on startup:
```
in net.logstash.logback.appender.LogstashTcpSocketAppender[BOOT] - Unable start disruptor java.lang.NoSuchMethodError: ch.qos.logback.core.encoder.Encoder.init(Ljava/io/OutputStream;)V
	at java.lang.NoSuchMethodError: ch.qos.logback.core.encoder.Encoder.init(Ljava/io/OutputStream;)V
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:539)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:488)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:332)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:184)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:113)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at 	at java.lang.Thread.run(Thread.java:745)
```

see logback commit log:
https://github.com/qos-ch/logback/commit/e2a9429c293ddc55b2a0f771c376b1bf3b00c8ba#diff-6016b292fde98b9e7ed5c04a79bd96f2

**Comment by openwms** [comment]
Closed. Looks like I had a dependency clash and somehow version 4.6 was used. Can't reproduce with clean classpath 4.9 and LB 1.2.1
