### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lch/qos/logback/classic/LoggerContext;

### ISSUE THREAD

**Issue by amitghodke90** [logstash/logstash-logback-encoder#235]
07-10 13:21:12.183 13136-13136/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.amit.mqttdemo, PID: 13136
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lch/qos/logback/classic/LoggerContext;
                                                       at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:60)
                                                       at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:53)
                                                       at org.slf4j.impl.StaticLoggerBinder.getSingleton(StaticLoggerBinder.java:68)
                                                       at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
                                                       at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
                                                       at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
                                                       at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
                                                       at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.<clinit>(KuraBirthCertificateModule.java:35)
                                                       at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.newBuilder(KuraBirthCertificateModule.java:105)
                                                       at org.eclipse.kapua.gateway.client.profile.kura.KuraMqttProfile.build(KuraMqttProfile.java:82)
                                                       at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:49)
                                                       at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:38)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "ch.qos.logback.classic.LoggerContext" on path: DexPathList[[zip file "/data/app/com.example.amit.mqttdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.amit.mqttdemo-1/lib/x86, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:60) 
                                                       at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:53) 
                                                       at org.slf4j.impl.StaticLoggerBinder.getSingleton(StaticLoggerBinder.java:68) 
                                                       at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189) 
                                                       at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112) 
                                                       at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105) 
                                                       at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235) 
                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208) 
                                                       at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221) 
                                                       at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.<clinit>(KuraBirthCertificateModule.java:35) 
                                                       at org.eclipse.kapua.gateway.client.kura.KuraBirthCertificateModule.newBuilder(KuraBirthCertificateModule.java:105) 
                                                       at org.eclipse.kapua.gateway.client.profile.kura.KuraMqttProfile.build(KuraMqttProfile.java:82) 
                                                       at com.example.amit.mqttdemo.KapuaConnectDemoActivity.Connect(KapuaConnectDemoActivity.java:49) 
                                                       at com.example.amit.mqttdemo.KapuaConnectDemoActivity.onCreate(KapuaConnectDemoActivity.java:38) 
                                                       at android.app.Activity.performCreate(Activity.java:6679) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by philsttr** [comment]
You need to include logback-classic on your classpath
