### ISSUE TITLE
logstash-logback-encoder is not supported with SpringBoot 1.2.7.RELEASE

### ISSUE THREAD

**Issue by fighter23rd** [logstash/logstash-logback-encoder#254]
When I added the logstash-logback-encoder  (version 4.11 ) it is not working with SpringBoot 1.2.7 version.

**spring-logback.xml :**
```xml

<springProfile name="Devl,Qual,Cert,SitQ,SitC">
		  <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
      <destination>abc:4560</destination>

      <!-- encoder is required -->
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
  		 <encoder class="net.logstash.logback.encoder.LogstashEncoder">
             <customFields>{ "api_name":"my-api"}</customFields>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
				-
				<level>WARN</level>
				-
				<onMatch>DENY</onMatch>
				-
				<onMismatch>ACCEPT</onMismatch>
				-
			</filter>
  	</appender>
  		
  	<logger name="com.deere.moci.pricing">

			</filter>
  	</appender>
  		
  	<logger name="com.deere.moci.pricing">
   	<level value="INFO" />
    		<appender-ref ref="stash"/>
 	</logger>

	</springProfile>
```
**Error I faced**
```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/Context;Lch/qos/logback/core/pattern/Converter;)V
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:86)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:50)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
	at com.deere.moci.pricing.MociPricingStartUp.main(MociPricingStartUp.java:16)
Exception in thread "main" java.lang.AbstractMethodError: ch.qos.logback.classic.pattern.EnsureExceptionHandling.process(Lch/qos/logback/core/Context;Lch/qos/logback/core/pattern/Converter;)V
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:86)
	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at org.springframework.boot.logging.logback.LogbackConfigurator.start(LogbackConfigurator.java:111)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.consoleAppender(DefaultLogbackConfiguration.java:105)
	at org.springframework.boot.logging.logback.DefaultLogbackConfiguration.apply(DefaultLogbackConfiguration.java:63)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadDefaults(LogbackLoggingSystem.java:106)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:53)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:217)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:185)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:164)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:144)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:286)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
	at com.deere.moci.pricing.MociPricingStartUp.main(MociPricingStartUp.java:16)
```

**Comment by philsttr** [comment]
Please make sure the version of logback-classic and logback-core you are using are in sync.  This just looks like a mismatch of the logback-classic and logback-core libraries.

You can force the same version by using [dependency management](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management)

**Comment by fighter23rd** [comment]
Thanks for your reply, But I tried this as well when I sync the logback-classic and logback-core via dependency management I see exception is not coming but it is not pushing logs to logstash as well.

<dependencyManagement>
		<dependencies>
			<dependency>
			    <groupId>ch.qos.logback</groupId>
			    <artifactId>logback-classic</artifactId>
			    <version>1.1.11</version>
   			</dependency>
    
			<dependency>
			    <groupId>ch.qos.logback</groupId>
			    <artifactId>logback-core</artifactId>
			    <version>1.1.11</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

<dependencies>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>4.11</version>
	<dependencies>

**Comment by philsttr** [comment]
This issue was originally due to mismatched classic/core versions.

If you are running into other issues, please open another issue with more details (logback configuration used, example application that can reproduce the problem, etc).
