### ISSUE TITLE
problem about tcp

### ISSUE THREAD

**Issue by zhenght888** [logstash/logstash-logback-encoder#310]
We using logstash-logback-encoder  to push logs to logstash,
and using logstash-input-tcp to collect them,
the  message include many chars of "\n",
### like this:
![image](https://user-images.githubusercontent.com/23733273/48062837-25632f00-e1fe-11e8-9e48-60ff4d130d47.png)

### the original text:
```
2018-11-06 19:46:27.767[log-crm-msc][synergism-rest][127.0.0.1][WARN][DubboSaveRegistryCache-thread-1]com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry||-> [DUBBO] Failed to save registry store file, cause: No space left on device, dubbo version: 2.8.5, current host: 136.142.33.7
java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        at java.io.Writer.write(Writer.java:157)
        at java.util.Properties.store0(Properties.java:840)
```

### the version of jar:
```
       <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>5.2</version>
        </dependency>
```

### the configuration of logstash:
```
input {
  tcp {
    port => 9351
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601}"
      negate => true
      what => "previous"
      charset => "UTF-8"
    }
  }
}
```

Please tell me how to push logs without "\n",
Thanks.

**Comment by osigida** [comment]
you can use logstash for that https://discuss.elastic.co/t/remove-n-and-t-from-message/142620
