### ISSUE TITLE
JaxbAnnotationModule not a subtype 

### ISSUE THREAD

**Issue by Michenux** [logstash/logstash-logback-encoder#324]
Hi,

I get the following error in my project when using logstash-logback-encoder 5.3 in my project. 
My project includes jackson 2.9.8 (same version), logback-classic 1.2.3 and slf4j 1.7.26.

```
Caused by: java.lang.RuntimeException: User code thrown exception: 
java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider 
com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not a subtype at 
java.util.ServiceLoader.fail(ServiceLoader.java:239) at 
java.util.ServiceLoader.access$300(ServiceLoader.java:185) at 
java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376) at 
java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) at 
java.util.ServiceLoader$1.next(ServiceLoader.java:480) at 
com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:994) at 
com.fasterxml.jackson.databind.ObjectMapper.findModules(ObjectMapper.java:978) at 
com.fasterxml.jackson.databind.ObjectMapper.findAndRegisterModules(ObjectMapper.java:1028) at 
net.logstash.logback.composite.CompositeJsonFormatter.createJsonFactory(CompositeJsonFormatter.java:130) at 
net.logstash.logback.composite.CompositeJsonFormatter.start(CompositeJsonFormatter.java:104) at net.logstash.logback.LogstashFormatter.start(LogstashFormatter.java:154) at 
net.logstash.logback.encoder.CompositeJsonEncoder.start(CompositeJsonEncoder.java:211) at 
ch.qos.logback.core.joran.action.NestedComplexPropertyIA.end(NestedComplexPropertyIA.java:161) at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309) at 
ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193) at 
ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179) at 
ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62) at 
ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165) at 
ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152) at 
ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110) at 
ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53) at 
ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75) at 
ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150) at 
org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84) at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55) at 
org.slf4j.LoggerFactory.bind(LoggerFactory.java:150) at 
org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124) at 
org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412) at 
org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357) at 
org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130) at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91) at 
org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:46) at 
org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:41) at 
org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657) at 
org.springframework.core.SimpleAliasRegistry.<init>(SimpleAliasRegistry.java:44)
```

**Comment by Michenux** [comment]
I was missing the following libraries :

```
               <dependency>
                       <groupId>com.fasterxml.jackson.module</groupId>
                       <artifactId>jackson-module-jaxb-annotations</artifactId>
              </dependency>
               <dependency>
                       <groupId>com.fasterxml.jackson.datatype</groupId>
                       <artifactId>jackson-datatype-joda</artifactId>
               </dependency>
```

I think you can close the issue.

**Comment by bric3** [comment]
@AnilKumarReddyBelum it's likely a classloader issue, for example the `ObjectMapper` and `Module` are loaded by _ClassLoader A_, but the current classloader Thread in the thread is `ClassLoader B`, so when the module class `JaxbAnnotationModule` is loaded (as well as it's ancestors, in particular `Module`) by _ClassLoader B_ which makes it incompatible with classes loaded by _Class Loader A_. The `ServiceLoader` thus fails with 

```text
java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule not a subtype
```

**Comment by brenuart** [comment]
@AnilKumarReddyBelum also make sure all the Jackson libraries are aligned on the same version.
If the problem persists, post a complete stack trace (from the root) and if possible an indication of from which thread it originates. Additional information about your runtime environment might be handy (is it a SpringBoot app, Spring version? how is the logging system configured/initialized, etc).
