### ISSUE TITLE
JSON serialization of fields causes exception

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#360]
It looks like the composite encoder is very aggressive in how it serializes fields in exceptions, and in some cases this can lead to exceptions.

Seen here is an exception caused from a toString which then kicks off an exception in Jackson serialization for the same reason (because JSSE):

```
10:03:44,493 |-WARN in net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder@73d70bdc - Error encountered while encoding log event. Event: com.tersesystems.logback.uniqueid.UniqueIdLoggingEvent@5db0e443 com.fasterxml.jackson.databind.JsonMappingException: SSLContextImpl is not initialized (through reference chain: javax.net.ssl.SSLContext["socketFactory"])
	at com.fasterxml.jackson.databind.JsonMappingException: SSLContextImpl is not initialized (through reference chain: javax.net.ssl.SSLContext["socketFactory"])
	at 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at 	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at 	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2656)
	at 	at com.fasterxml.jackson.core.util.JsonGeneratorDelegate.writeObject(JsonGeneratorDelegate.java:383)
	at 	at net.logstash.logback.marker.ObjectAppendingMarker.writeFieldValue(ObjectAppendingMarker.java:94)
	at 	at net.logstash.logback.marker.SingleFieldAppendingMarker.writeTo(SingleFieldAppendingMarker.java:84)
	at 	at net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:76)
	at 	at net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:43)
	at 	at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)
	at 	at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:188)
	at 	at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:165)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:122)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:34)
	at 	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at 	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at 	at net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:54)
	at 	at net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:50)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:339)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:327)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: SSLContextImpl is not initialized
	at 	at sun.security.ssl.SSLContextImpl.engineGetSocketFactory(SSLContextImpl.java:177)
	at 	at javax.net.ssl.SSLContext.getSocketFactory(SSLContext.java:294)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
	at 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at 	... 32 common frames omitted

**Comment by philsttr** [comment]
What log statement was used in this case?

Specifically, what object are you passing into the structured argument for jackson to serialize?

You mention an exception from toString(), but I don't see any calls to toString() in the stacktrace.  Can you clarify this?

**Comment by wsargent** [comment]
You're right, it's not a `toString` method call.  I think it may be the static SSLContext init method, which returns the SSLContext itself as a return value.  This is happening through instrumentation:

https://github.com/tersesystems/terse-logback/blob/master/logback-bytebuddy/src/main/java/com/tersesystems/logback/bytebuddy/impl/Exit.java#L40

**Comment by wsargent** [comment]
Yep, here's the exception:

```json

{
  "id" : "FcNrhoPf5WA6O0Qbm7EAAA",
  "sequence" : 12,
  "@timestamp" : "2019-09-11T17:03:44.380Z",
  "@version" : "1",
  "message" : "throwing: javax.net.ssl.SSLContext.getSocketFactory() with arguments=[] ! thrown=java.lang.IllegalStateException: SSLContextImpl is not initialized",
  "logger_name" : "javax.net.ssl.SSLContext",
  "thread_name" : "logback-appender-ASYNC_JSONFILE-2",
  "level" : "ERROR",
  "level_value" : 40000,
  "stack_hash" : "10dd9793",
  "name" : "javax.net.ssl.SSLContext.getSocketFactory()",
  "trace.span_id" : "707aa86b-a1c7-4e8f-9de9-c7b3d0ff2e22",
  "duration_ms" : 1,
  "class" : "javax.net.ssl.SSLContext",
  "method" : "getSocketFactory",
  "signature" : "()",
  "arguments" : [ ],
  "thrown" : {
    "cause" : null,
    "stackTrace" : [ {
      "methodName" : "engineGetSocketFactory",
      "fileName" : "SSLContextImpl.java",
      "lineNumber" : 177,
      "className" : "sun.security.ssl.SSLContextImpl",
      "nativeMethod" : false
    }, {
      "methodName" : "getSocketFactory",
      "fileName" : "SSLContext.java",
      "lineNumber" : 294,
      "className" : "javax.net.ssl.SSLContext",
      "nativeMethod" : false
    }, {
      "methodName" : "invoke0",
      "fileName" : "NativeMethodAccessorImpl.java",
      "lineNumber" : -2,
      "className" : "sun.reflect.NativeMethodAccessorImpl",
      "nativeMethod" : true
    }, {
      "methodName" : "invoke",
      "fileName" : "NativeMethodAccessorImpl.java",
      "lineNumber" : 62,
      "className" : "sun.reflect.NativeMethodAccessorImpl",
      "nativeMethod" : false
    }, {
      "methodName" : "invoke",
      "fileName" : "DelegatingMethodAccessorImpl.java",
      "lineNumber" : 43,
      "className" : "sun.reflect.DelegatingMethodAccessorImpl",
      "nativeMethod" : false
    }, {
      "methodName" : "invoke",
      "fileName" : "Method.java",
      "lineNumber" : 498,
      "className" : "java.lang.reflect.Method",
      "nativeMethod" : false
    }, {
      "methodName" : "serializeAsField",
      "fileName" : "BeanPropertyWriter.java",
      "lineNumber" : 688,
      "className" : "com.fasterxml.jackson.databind.ser.BeanPropertyWriter",
      "nativeMethod" : false
    }, {
      "methodName" : "serializeFields",
      "fileName" : "BeanSerializerBase.java",
      "lineNumber" : 719,
      "className" : "com.fasterxml.jackson.databind.ser.std.BeanSerializerBase",
      "nativeMethod" : false
    }, {
      "methodName" : "serialize",
      "fileName" : "BeanSerializer.java",
      "lineNumber" : 155,
      "className" : "com.fasterxml.jackson.databind.ser.BeanSerializer",
      "nativeMethod" : false
    }, {
      "methodName" : "_serialize",
      "fileName" : "DefaultSerializerProvider.java",
      "lineNumber" : 480,
      "className" : "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "nativeMethod" : false
    }, {
      "methodName" : "serializeValue",
      "fileName" : "DefaultSerializerProvider.java",
      "lineNumber" : 319,
      "className" : "com.fasterxml.jackson.databind.ser.DefaultSerializerProvider",
      "nativeMethod" : false
    }, {
      "methodName" : "writeValue",
      "fileName" : "ObjectMapper.java",
      "lineNumber" : 2656,
      "className" : "com.fasterxml.jackson.databind.ObjectMapper",
      "nativeMethod" : false
    }, {
      "methodName" : "writeObject",
      "fileName" : "JsonGeneratorDelegate.java",
      "lineNumber" : 383,
      "className" : "com.fasterxml.jackson.core.util.JsonGeneratorDelegate",
      "nativeMethod" : false
    }, {
      "methodName" : "writeFieldValue",
      "fileName" : "ObjectAppendingMarker.java",
      "lineNumber" : 94,
      "className" : "net.logstash.logback.marker.ObjectAppendingMarker",
      "nativeMethod" : false
    }, {
      "methodName" : "writeTo",
      "fileName" : "SingleFieldAppendingMarker.java",
      "lineNumber" : 84,
      "className" : "net.logstash.logback.marker.SingleFieldAppendingMarker",
      "nativeMethod" : false
    }, {
      "methodName" : "writeTo",
      "fileName" : "ArgumentsJsonProvider.java",
      "lineNumber" : 76,
      "className" : "net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider",
      "nativeMethod" : false
    }, {
      "methodName" : "writeTo",
      "fileName" : "ArgumentsJsonProvider.java",
      "lineNumber" : 43,
      "className" : "net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider",
      "nativeMethod" : false
    }, {
      "methodName" : "writeTo",
      "fileName" : "JsonProviders.java",
      "lineNumber" : 77,
      "className" : "net.logstash.logback.composite.JsonProviders",
      "nativeMethod" : false
    }, {
      "methodName" : "writeEventToGenerator",
      "fileName" : "CompositeJsonFormatter.java",
      "lineNumber" : 188,
      "className" : "net.logstash.logback.composite.CompositeJsonFormatter",
      "nativeMethod" : false
    }, {
      "methodName" : "writeEventToOutputStream",
      "fileName" : "CompositeJsonFormatter.java",
      "lineNumber" : 165,
      "className" : "net.logstash.logback.composite.CompositeJsonFormatter",
      "nativeMethod" : false
    }, {
      "methodName" : "encode",
      "fileName" : "CompositeJsonEncoder.java",
      "lineNumber" : 122,
      "className" : "net.logstash.logback.encoder.CompositeJsonEncoder",
      "nativeMethod" : false
    }, {
      "methodName" : "encode",
      "fileName" : "CompositeJsonEncoder.java",
      "lineNumber" : 34,
      "className" : "net.logstash.logback.encoder.CompositeJsonEncoder",
      "nativeMethod" : false
    }, {
      "methodName" : "subAppend",
      "fileName" : "OutputStreamAppender.java",
      "lineNumber" : 230,
      "className" : "ch.qos.logback.core.OutputStreamAppender",
      "nativeMethod" : false
    }, {
      "methodName" : "subAppend",
      "fileName" : "RollingFileAppender.java",
      "lineNumber" : 235,
      "className" : "ch.qos.logback.core.rolling.RollingFileAppender",
      "nativeMethod" : false
    }, {
      "methodName" : "append",
      "fileName" : "OutputStreamAppender.java",
      "lineNumber" : 102,
      "className" : "ch.qos.logback.core.OutputStreamAppender",
      "nativeMethod" : false
    }, {
      "methodName" : "doAppend",
      "fileName" : "UnsynchronizedAppenderBase.java",
      "lineNumber" : 84,
      "className" : "ch.qos.logback.core.UnsynchronizedAppenderBase",
      "nativeMethod" : false
    }, {
      "methodName" : "appendLoopOnAppenders",
      "fileName" : "AppenderAttachableImpl.java",
      "lineNumber" : 51,
      "className" : "ch.qos.logback.core.spi.AppenderAttachableImpl",
      "nativeMethod" : false
    }, {
      "methodName" : "onEvent",
      "fileName" : "DelegatingAsyncDisruptorAppender.java",
      "lineNumber" : 54,
      "className" : "net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler",
      "nativeMethod" : false
    }, {
      "methodName" : "onEvent",
      "fileName" : "DelegatingAsyncDisruptorAppender.java",
      "lineNumber" : 50,
      "className" : "net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler",
      "nativeMethod" : false
    }, {
      "methodName" : "onEvent",
      "fileName" : "AsyncDisruptorAppender.java",
      "lineNumber" : 339,
      "className" : "net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler",
      "nativeMethod" : false
    }, {
      "methodName" : "onEvent",
      "fileName" : "AsyncDisruptorAppender.java",
      "lineNumber" : 327,
      "className" : "net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler",
      "nativeMethod" : false
    }, {
      "methodName" : "processEvents",
      "fileName" : "BatchEventProcessor.java",
      "lineNumber" : 168,
      "className" : "net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "BatchEventProcessor.java",
      "lineNumber" : 125,
      "className" : "net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor",
      "nativeMethod" : false
    }, {
      "methodName" : "call",
      "fileName" : "Executors.java",
      "lineNumber" : 511,
      "className" : "java.util.concurrent.Executors$RunnableAdapter",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "FutureTask.java",
      "lineNumber" : 266,
      "className" : "java.util.concurrent.FutureTask",
      "nativeMethod" : false
    }, {
      "methodName" : "access$201",
      "fileName" : "ScheduledThreadPoolExecutor.java",
      "lineNumber" : 180,
      "className" : "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "ScheduledThreadPoolExecutor.java",
      "lineNumber" : 293,
      "className" : "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask",
      "nativeMethod" : false
    }, {
      "methodName" : "runWorker",
      "fileName" : "ThreadPoolExecutor.java",
      "lineNumber" : 1149,
      "className" : "java.util.concurrent.ThreadPoolExecutor",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "ThreadPoolExecutor.java",
      "lineNumber" : 624,
      "className" : "java.util.concurrent.ThreadPoolExecutor$Worker",
      "nativeMethod" : false
    }, {
      "methodName" : "run",
      "fileName" : "Thread.java",
      "lineNumber" : 748,
      "className" : "java.lang.Thread",
      "nativeMethod" : false
    } ],
    "message" : "SSLContextImpl is not initialized",
    "localizedMessage" : "SSLContextImpl is not initialized",
    "suppressed" : [ ]
  },
  "exception" : [ {
    "name" : "java.lang.IllegalStateException",
    "properties" : {
      "message" : "SSLContextImpl is not initialized"
    }
  } ],
  "stack_trace" : "<#10dd9793> java.lang.IllegalStateException: SSLContextImpl is not initialized\n\tat sun.security.ssl.SSLContextImpl.engineGetSocketFactory(SSLContextImpl.java:177)\n\tat javax.net.ssl.SSLContext.getSocketFactory(SSLContext.java:294)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)\n\tat com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)\n\tat com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)\n\tat com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)\n\tat com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2656)\n\tat com.fasterxml.jackson.core.util.JsonGeneratorDelegate.writeObject(JsonGeneratorDelegate.java:383)\n\tat net.logstash.logback.marker.ObjectAppendingMarker.writeFieldValue(ObjectAppendingMarker.java:94)\n\tat net.logstash.logback.marker.SingleFieldAppendingMarker.writeTo(SingleFieldAppendingMarker.java:84)\n\tat net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:76)\n\tat net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider.writeTo(ArgumentsJsonProvider.java:43)\n\tat net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)\n\tat net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:188)\n\tat net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:165)\n\tat net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:122)\n\tat net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:34)\n\tat ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)\n\tat ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)\n\tat ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)\n\tat ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)\n\tat ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)\n\tat net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:54)\n\tat net.logstash.logback.appender.DelegatingAsyncDisruptorAppender$DelegatingEventHandler.onEvent(DelegatingAsyncDisruptorAppender.java:50)\n\tat net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:339)\n\tat net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:327)\n\tat net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)\n\tat net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"
}
```

**Comment by philsttr** [comment]
Ok.  The recommended practice for logging exceptions is to just include the exception as an extra (regular) argument like you would [normally log exceptions with slf4j](https://www.baeldung.com/slf4j-log-exceptions).

In other words, do _not_ include the exception inside a structured argument.

If you include an exception as a structured argument, then Jackson just tries to serialize the exception object to JSON just like any other POJO.

Specifically, remove [this structured argument](https://github.com/tersesystems/terse-logback/blob/66f67da2d0dc2dde81bd8931852a79025c36f4b2/logback-bytebuddy/src/main/java/com/tersesystems/logback/bytebuddy/impl/Exit.java#L49) from the code you linked.

If you _do_ want to log the exception as a structured argument, then you'll need to configure Jackson to serialize whatever exceptions you're logging.  For example, you could add a `JsonFactoryDecorator` that registers a custom serializer.

**Comment by wsargent** [comment]
Okay, thanks for the background and explanation.  It looks like #304 covers this so I will close this bug.
