### ISSUE TITLE
Composite Encoder/Layout throws error with maxLength = "full"

### ISSUE THREAD

**Issue by konstantinblaesi** [logstash/logstash-logback-encoder#371]
We're using a [configuration like this](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout) in our logback.xml. We've recently changed
`<maxLength>2048</maxLength>` to `<maxLength>full</maxLength>`. While two collegues do not see any errors, my machine shows this trace:
```
16:57:00,260 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.StackTraceJsonProvider] for [stackTrace] property
16:57:00,275 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@40f70521 - Failed to set property [maxLength] to value "full".  ch.qos.logback.core.util.PropertySetterException: Conversion to type [int] failed. 
	at ch.qos.logback.core.util.PropertySetterException: Conversion to type [int] failed. 
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:124)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:98)
	at 	at ch.qos.logback.core.joran.action.NestedBasicPropertyIA.body(NestedBasicPropertyIA.java:95)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at 	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at 	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:195)
	at 	at com.sample.DemoApplication.main(DemoApplication.java:10)
Caused by: java.lang.NumberFormatException: For input string: "full"
	at 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at 	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at 	at java.base/java.lang.Integer.<init>(Integer.java:1096)
	at 	at ch.qos.logback.core.joran.util.StringToObjectConverter.convertArg(StringToObjectConverter.java:61)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:122)
	at 	... 23 common frames omitted
```
Do you know what might be causing this?

**Comment by philsttr** [comment]
You can't use `<maxLength>full</maxLength>`.  The `maxLength` element only [accepts integer values](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L580).

The `full`  special keyword is only usable when it the converter is used in a `conversionRule` as described in the [javadoc for ShortenedThrowableConverter](https://github.com/logstash/logstash-logback-encoder/blob/05d3ae9cb434ebbc18211c861c93cb22f076338d/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L58-L84).  They don't currently work when configured as part of an encoder, as you have found out.

**Comment by konstantinblaesi** [comment]
Ok then to achieve the `full` setting, I'd just add `<maxLength>2147483647</maxLength>` to [match what would be set](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L95) if if `full` would be used in a `conversionRule``? What still confuses me is why two other devs cannot reproduce this error...

**Comment by philsttr** [comment]
Correct.  And I don't know how it is working for them either.  It shouldn't.

You could set a breakpoint [here](https://github.com/logstash/logstash-logback-encoder/blob/05d3ae9cb434ebbc18211c861c93cb22f076338d/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L581) to see if the maxLength is ever being set.
