### ISSUE TITLE
Unable to Micronaut Properties in destination field in the logback.xml

### ISSUE THREAD

**Issue by gokulraghu** [logstash/logstash-logback-encoder#407]
I am working on a logstash encoder via TCP. I am integrating logstash with micronaut service for ELK stack. In logback.xml, we need to externalize the logstash hostname and port values. In SpringBoot, we will be using the below configuration in logback.xml to use the application property.

```xml
<configuration>
 <springProperty scope="context" name="logstashHost" source="logstash.hostname"/>
<springProperty scope="context" name="logstashPort" source="logstash.port"/>

<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
<destination>${logstashHost}:${logstashPort}</destination>
</configuration>
```

On similar lines i tried as given  below to read the  logstash properties that are present externally using the spring config service based on environment profile.

```xml
<configuration>
	<property name="logstash_hostname" source="logstash.tcpConfig.hostname" />
	<property name="logstash_port" source="logstash.tcpConfig.port" />

	<!--Setting appender for logs to be pushed to logstash directly over TCP. -->
	<appender name="stash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		<destination>${logstash_hostname}:${logstash_port}</destination>
		<encoder class="net.logstash.logback.encoder.LogstashEncoder">
			<fieldNames>
				<message>log_message</message>
			</fieldNames>
		</encoder>
	</appender>
	<root level="info">
		<appender-ref ref="stash" />
	</root>
</configuration>
```

The below property is present externally in {application-name}-{env}.yml
```yml
logstash:
  tcpConfig: 
    hostname: xx.xx.xx.xx
    port: xxxxx
```

During start-up, i get the below exception:

```error
ERROR in ch.qos.logback.core.joran.util.PropertySetter@76ed5528 - Could not invoke method addDestination in class net.logstash.logback.appender.LogstashTcpSocketAppender with parameter of type java.lang.String java.lang.reflect.InvocationTargetException
	at java.lang.reflect.InvocationTargetException
 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at 	at ch.qos.logback.core.joran.util.PropertySetter.invokeMethodWithSingleParameterOnThisObject(PropertySetter.java:251)
 	at 	at ch.qos.logback.core.joran.util.PropertySetter.addBasicProperty(PropertySetter.java:282)
 	at 	at ch.qos.logback.core.joran.action.NestedBasicPropertyIA.body(NestedBasicPropertyIA.java:98)
 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
 	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
 	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
 	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
 	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
 	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
 	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
 	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
 	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
 	at 	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:46)
 	at 	at com.comcast.ods.Application.main(Application.java:18)
 Caused by: java.lang.IllegalArgumentException: Invalid destination 'logstash_hostname_IS_UNDEFINED:logstash_port_IS_UNDEFINED': unparseable value (expected format 'host[:port]').
 	at 	at net.logstash.logback.appender.destination.DestinationParser.parse(DestinationParser.java:62)
 	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender.addDestination(AbstractLogstashTcpSocketAppender.java:953)
 	at 	... 25 common frames omitted
 ```

Thanks ,
Gokul

**Comment by philsttr** [comment]
This does not appear to be a problem with logstash-logback-encoder. 

logback is just unable to determine the value of `logstash_port`

I believe for the spring-boot logback integration to work, you need to use `springProperty` instead of `property` when defining those properties.

**Comment by gokulraghu** [comment]
Hi,

The framework I use for the application is micronaut which is similar to spring boot. I tried injecting the destination using the mentioned code but it isn't working

**Comment by philsttr** [comment]
Ok, logback's `property` element does not support a `source` attribute as far as I'm aware.

Does micronaut provide something similar to spring boot's `springProperty` ?

If not, then I'd recommend filing a feature request for micronaut to provide logback integration similar to the way spring boot does it.

In any case, this is not a problem with logstash-logback-encoder.   You'll need to sort this out between logback and micronaut
