### ISSUE TITLE
Doesn't seem to be possible to test with slf4j-test

### ISSUE THREAD

**Issue by jamietanna** [logstash/logstash-logback-encoder#526]
**Describe the bug**

It does not appear possible to use [slf4j-test](https://projects.lidalia.org.uk/slf4j-test/index.html) to add logging tests while using this library, as logback needs to be excluded from the classpath, so slf4j-test is prioritised.

**To Reproduce**

Example project can be found at [logstash-slf4j-test](https://gitlab.com/jamietanna/logstash-slf4j-test), and running `./gradlew clean test` results in:

```
ch/qos/logback/core/status/Status
java.lang.NoClassDefFoundError: ch/qos/logback/core/status/Status
	at me.jvt.hacking.ClassThatLogs.methodToLog(ClassThatLogs.java:13)
	at me.jvt.hacking.ClassThatLogsTest.testLogs(ClassThatLogsTest.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.status.Status
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 92 more
```

**Expected behavior**

Unit tests to be possible.

**Additional context**

When not excluding logback dependencies:

```
ClassThatLogsTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/jamie/.gradle/caches/modules-2/files-2.1/uk.org.lidalia/slf4j-test/1.2.0/2f5f40ac2f912f215334a1c9d2f52bbc378eda0d/slf4j-test-1.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/jamie/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [uk.org.lidalia.slf4jtest.TestLoggerFactory]

ClassThatLogsTest > testLogs() FAILED
    java.lang.AssertionError: 
    Expecting ArrayList:
      [LoggingEvent[level=INFO,mdc={},marker=Optional.absent(),throwable=Optional.absent(),message=Message,arguments=[object=me.jvt.hacking.ClassThatLogs@5739b609]]]
    to contain:
      [LoggingEvent[level=INFO,mdc={},marker=Optional.absent(),throwable=Optional.absent(),message=Message,arguments=[]]]
    but could not find the following element(s):
      [LoggingEvent[level=INFO,mdc={},marker=Optional.absent(),throwable=Optional.absent(),message=Message,arguments=[]]]
        at me.jvt.hacking.ClassThatLogsTest.testLogs(ClassThatLogsTest.java:19)
```

When excluding just `logback-core`:

```
ClassThatLogsTest STANDARD_ERROR
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/home/jamie/.gradle/caches/modules-2/files-2.1/uk.org.lidalia/slf4j-test/1.2.0/2f5f40ac2f912f215334a1c9d2f52bbc378eda0d/slf4j-test-1.2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/home/jamie/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [uk.org.lidalia.slf4jtest.TestLoggerFactory]

ClassThatLogsTest > testLogs() FAILED
    java.lang.NoClassDefFoundError: ch/qos/logback/core/status/Status
        at me.jvt.hacking.ClassThatLogs.methodToLog(ClassThatLogs.java:13)
        at me.jvt.hacking.ClassThatLogsTest.testLogs(ClassThatLogsTest.java:17)

        Caused by:
        java.lang.ClassNotFoundException: ch.qos.logback.core.status.Status
            at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
            ... 2 more
```

When excluding just `logback-classic`:

```
ClassThatLogsTest > testLogs() FAILED
    java.lang.NoClassDefFoundError: ch/qos/logback/core/status/Status
        at me.jvt.hacking.ClassThatLogs.methodToLog(ClassThatLogs.java:13)
        at me.jvt.hacking.ClassThatLogsTest.testLogs(ClassThatLogsTest.java:17)

        Caused by:
        java.lang.ClassNotFoundException: ch.qos.logback.core.status.Status
            at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
            ... 2 more
```

I've also given it a go by trying to create a shaded JAR that excludes the `org/slf4j/impl` classes, but that didn't seem to quite do it - happy to be pointed out how I've done it wrong though! 

* logstash-logback-encoder version: `6.6`
* logback version: `1.2.3`
* jackson version: `2.12.0`
* java version: `1.8`

**Comment by jamietanna** [comment]
Ooh so it looks like this may actually be to do with the way that spring-boot-starter-logging works (in my example) - which [I've amended in the sample code](https://gitlab.com/jamietanna/logstash-slf4j-test/-/commit/d7d1f29cb6e3b4fc640052715f66a39f453fb2b0).

Keeping an explicit dependency on -core seems to sort it :smile:

Just seeing on a regular Spring Boot project whether I can resolve it

**Comment by jamietanna** [comment]
Closing as this appears to be a Spring Boot issue.
