### ISSUE TITLE
How to solve this problem？-》ScheduledThreadPoolExecutor$ScheduledFutureTask@21ab905 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d4eb977[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0] 	at 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) 	at 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)

### ISSUE THREAD

**Issue by yz-1130** [logstash/logstash-logback-encoder#572]
JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:NewRatio=1 -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:CMSInitiatingOccupancyFraction=70 -Xms1433m -Xmx1433m
14:11:15,292 |-WARN in com.pousheng.marketing.web.config.AutoLogstashTcpSocketAppender[logstash] - Log destination 10.XXXXX:5044: connection failed. java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@21ab905 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d4eb977[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@21ab905 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1d4eb977[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
	at 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:549)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:648)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender.scheduleReaderCallable(AbstractLogstashTcpSocketAppender.java:994)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:753)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:639)
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:390)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at 	at java.lang.Thread.run(Thread.java:748)

**Comment by brenuart** [comment]
Could you please tell me which version of logstash-logback-encoder you are using?
Also, it looks like the appender was shutdown or was in the process of being shutdown - do you confirm?

Chances are the appender has emitted additional warn status messages before the exception you report occurred. Please provide them as well - they may contain valuable information that could help to troubleshoot the issue.

Finally, it seems you are using a custom version of the LogstashTcpSocketAppender. Could you briefly describe how it defers from the original version and/or provide the code?
