### ISSUE TITLE
AsyncDisruptorAppender won't shutdown when backlog can't be cleared

### ISSUE THREAD

**Issue by evpaassen** [logstash/logstash-logback-encoder#89]
if the `Disruptor` has a backlog, the `AsyncDisruptorAppender` won't shutdown.

`AsyncDisruptorAppender` calls `this.disruptor.shutdown();` without a timeout, so it will wait until the backlog is empty. If the logstash host is not reachable (and never will be), the backlog will never be empty, but the `Disruptor` will busy-wait (!) until it is.

So I think there should be a timeout, possibly configurable.

**Comment by evpaassen** [comment]
Thread dump:
```
"main" #1 prio=5 os_prio=0 tid=0x00000000021db800 nid=0x27f0 runnable [0x000000000268e000]
   java.lang.Thread.State: RUNNABLE
	at net.logstash.logback.encoder.com.lmax.disruptor.dsl.ConsumerRepository.getLastSequenceInChain(ConsumerRepository.java:70)
	at net.logstash.logback.encoder.com.lmax.disruptor.dsl.Disruptor.hasBacklog(Disruptor.java:411)
	at net.logstash.logback.encoder.com.lmax.disruptor.dsl.Disruptor.shutdown(Disruptor.java:338)
	at net.logstash.logback.encoder.com.lmax.disruptor.dsl.Disruptor.shutdown(Disruptor.java:317)
	at net.logstash.logback.appender.AsyncDisruptorAppender.stop(AsyncDisruptorAppender.java:323)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.detachAndStopAllAppenders(AppenderAttachableImpl.java:104)
	at ch.qos.logback.classic.Logger.detachAndStopAllAppenders(Logger.java:209)
	at ch.qos.logback.classic.Logger.recursiveReset(Logger.java:338)
	at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:213)
	at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:336)
	at ...
```

**Comment by philsttr** [comment]
Thanks for the report.  This is a dup of #82 and has already been fixed for the next release.
